version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      DATABASE_URL: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Aiuda@3312
      POSTGRES_DB: rafa_sales
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
    depends_on:
      - postgres

    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #para levantarlo hacemos docker-compose up